### ISSUE TITLE
Certificate is expired

### ISSUE THREAD

**Issue by cpcloud** [pgxn/pgxn#6]
This seems to prevent pgxn from working at all.

**Comment by theory** [comment]
Maybe there was a caching issue? The cert on pgxn.org shows this right now:

```
Expires: Wednesday, March 13, 2024 at 14:32:16 Eastern Daylight Time
```

**Comment by theory** [comment]
Ah, there was some lag in the auto-renewal process, so there was a gap of three hours or so. Will tweak the renewal period buffer.
